version: '2'

services:
  ppap_server:
    image: registry.cn-shenzhen.aliyuncs.com/ppap6pro/ppap_server:preview
    container_name: ppap_server
    restart: always
    ports:
      - "0.0.0.0:2333:2333"
    volumes:
      - /home/volume/PPAP_server/config/:/home/docker/PPAP_server/config/