version: '3'

services:
  ppap_server:
    image: jwchan1996/ppap_server:preview
    container_name: ppap_server
    restart: always
    ports:
      - "2333:2333"
    volumes:
      - /home/volume/PPAP_server/config/:/home/docker/PPAP_server/config/