version: '3'

services:
  ppap_server:
    imgae: jwchan1996/ppap_server:preview
    container_name: ppap_server
    restart: always
    ports:
      - "2333:2333"
    privileged: true
    volumes:
      - /home/volume/PPAP_server/config:/home/docker/PPAP_server/config