name: preview

on:
  push:
    branches:
      - master

jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Build Image
        env: 
          # docker hub 
          # DockerUsername: ${{ secrets.DOCKER_USERNAME  }}
          # DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
          # aliyun docker 
          AliyunDockerUsername: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          AliyunDockerPassword: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        run: |
          # docker hub
          # docker login -u $DockerUsername -p $DockerPassword
          # docker build -t jwchan1996/ppap_server:preview .
          # docker push jwchan1996/ppap_server:preview
          # aliyun docker
          docker login -u $AliyunDockerUsername -p $AliyunDockerPassword registry.cn-shenzhen.aliyuncs.com
          docker build -t registry.cn-shenzhen.aliyuncs.com/ppap6pro/ppap_server:preview .
          docker push registry.cn-shenzhen.aliyuncs.com/ppap6pro/ppap_server:preview
      
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: 10s

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: cd /home/docker/PPAP_server && docker-compose pull && docker-compose up -d