name: preview

on:
  push:
    branches:
      - master

jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Build Image
        env: 
          DockerUsername: ${{ secrets.DOCKER_USERNAME  }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DockerUsername -p $DockerPassword
          docker build -t jwchan1996/ppap_server:preview .
          docker push jwchan1996/ppap_server:preview
      
      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: 60s

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: cd /home/docker/PPAP_server && docker-compose pull && docker-compose up -d